### ISSUE TITLE
Development workflow

### ISSUE THREAD

**Issue by ahsanbagwan** [karan/jReddit#121]
I'm not sure whether this a valid question to be posed in the issues tab, but here goes. I've the project built using the command `mvn clean install`. Although after doing that I'm not sure what steps I should take if I want to implement an API call. 

I'm wondering what the basic workflow is like. So how do I run the project and the examples given here?

**Comment by sfat** [comment]
@ahsanbagwan well, first of all you would need to create class with a main method in it and copy paste what you see in the README
```
Connect a user

// Initialize REST Client
RestClient restClient = new HttpRestClient();
restClient.setUserAgent("bot/1.0 by name");

// Connect the user 
User user = new User(restClient, "username", "password");
try {
    user.connect();
} catch (Exception e) {
    e.printStackTrace();
}
```
After that under the user.connect you can move forward and use another example, which is present in the README, as well

```
// Handle to Submissions, which offers the basic API submission functionality
Submissions subms = new Submissions(restClient, user);

// Retrieve submissions of a submission
List<Submission> submissionsSubreddit = subms.ofSubreddit("programming", SubmissionSort.TOP, -1, 100, null, null, true);
```

Basically what you need to do is provide a valid username and password in this part instead of the hardcoded strings
```
User user = new User(restClient, "username", "password");
```

**Comment by ahsanbagwan** [comment]
OK this I believe is for consuming the API. Quite straightforward indeed. 

However, how would I go ahead if I need to implement API methods. For instance, if I want to take up the task of implementing `POST /api/clear_sessions` how would I go about that?

**Comment by sfat** [comment]
you can take a look at some closed pull requests, like this guy: https://github.com/karan/jReddit/pull/68 
Look a bit over it and let me know if you need some guidance

**Comment by ahsanbagwan** [comment]
Ok so got around the time to setup a newer and nicer version of Eclipse and to run that example as well. Thanks for that.

I have some queries about pull requests though: 
1) I've cloned the project the repo on my box a while ago. Do I need to make changes, test the new code and send in a pull request? Or does one have to fork and clone always?
2) The repo is a bit old and if by above point I do need to make changes to this repository do I need to `git pull` or something to sync changes?

**Comment by sfat** [comment]
hey @ahsanbagwan  I've been using this puppy to what you are asking: https://help.github.com/articles/syncing-a-fork/ . Let me know if you need help in regards with this. So basically, you need to update your fork because the fork that you make (aka clone) will not know about the master by default, so you'll need to sync it manually

**Comment by sfat** [comment]
@ahsanbagwan I'll close this guy if you have no more question. Reopen this if you need any help
